/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel_Management_system;

import static Hotel_Management_system.mysqlconnection.getConnection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhinav
 */
public class Hotel_system extends javax.swing.JFrame  {

    /**
     * Creates new form Hotel_system
     * @throws java.lang.ClassNotFoundException
     */
    public Hotel_system() throws ClassNotFoundException{
        initComponents();
       

    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxt7 = new javax.swing.JTextField();
        jtxt3 = new javax.swing.JTextField();
        jtxt4 = new javax.swing.JTextField();
        jtxt5 = new javax.swing.JTextField();
        jtxt6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        tax = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        jtotal = new javax.swing.JButton();
        Jbtndel = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jbtnupdate = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox<>();
        cb4 = new javax.swing.JComboBox<>();
        cb5 = new javax.swing.JComboBox<>();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        jtxt2 = new javax.swing.JTextField();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jtxt8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First_Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Address1:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Last_Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Customer Mobile:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" Post Code:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Meal:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 30));

        jtxt7.setName("Email"); // NOI18N
        getContentPane().add(jtxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 150, -1));

        jtxt3.setName("Last_Name"); // NOI18N
        getContentPane().add(jtxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, -1));

        jtxt4.setName("Address1"); // NOI18N
        getContentPane().add(jtxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, -1));

        jtxt5.setName(" Post Code"); // NOI18N
        jtxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt5ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, -1));

        jtxt6.setName("Customer Mobile"); // NOI18N
        jtxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt6ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nationality:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Date of Birth:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Gender:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ID Type:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Room Type:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Check-Out Date:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 120, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Check-In Date:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer_Ref", "First_Name", "Last_Name", "Address1", "Meal", "Post Code", "Customer Mobile", "Email", "Nationality", "DOB", "Gender", "Check-in Date", "Check-out Date", "Room Type", "Room Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 1030, 430));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel17.setText("TAX:");

        jLabel18.setText("TOTAL:");

        jLabel19.setText("SUB TOTAL:");

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });

        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        jtotal.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jtotal.setText("Total Cost");
        jtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotalActionPerformed(evt);
            }
        });

        Jbtndel.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        Jbtndel.setText("Delete");
        Jbtndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtndelActionPerformed(evt);
            }
        });

        jbtnexit.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jbtnexit.setText("Exit");
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });

        jbtnreset.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });

        jbtnupdate.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jbtnupdate.setText("Update");
        jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jbtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jbtnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1330, 150));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Room No.:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 80, 20));

        cb3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        getContentPane().add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 110, -1));

        cb4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Deluxe", "Suite" }));
        getContentPane().add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 110, -1));

        cb5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003", "004", "005", "101", "102", "103", "104", "105", "201", "202", "203", "204", "205" }));
        getContentPane().add(cb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 110, -1));

        cb1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driving Lic", "Passport", "Aadhar Card", "Student ID" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 130, -1));

        cb2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 110, -1));
        getContentPane().add(jtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, -1));
        getContentPane().add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 140, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 140, -1));

        jtxt8.setName("Email"); // NOI18N
        getContentPane().add(jtxt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 150, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLocaleChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLocaleChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLocaleChooser1ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed
private JFrame frame;
    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
            frame=new JFrame("Exit");
            if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Hotel Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
           {
               System.exit(0);
           }
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotalActionPerformed
       double SingleRoom=800.79;
       double DoubleRoom=1800.29;
       double DeluxeRoom=2460.88;
       double SuiteRoom=2800.96;
      // double Tax= 150.00;
       
       SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
       Date Check_In_Date=null;
       Date Check_Out_Date=null;
       String str="N/A";
       try
       {
           Check_In_Date=format.parse(format.format(jDateChooser1.getDate()));
            Check_Out_Date=format.parse(format.format(jDateChooser2.getDate()));
          
           
       }
       catch(ParseException | HeadlessException e)
       {
           e.printStackTrace();
           
       }
long checkdiff=Check_In_Date.getTime()-Check_Out_Date.getTime();        
boolean breakloop=true; 
 int daydiff=(int)(checkdiff /1000/60/60/24);
         /*  JTextField[] fields = new JTextField[7]; 
            fields[0] =jtxt1; 
            fields[1] =jtxt2;
            fields[2] =jtxt3;
            fields[3] =jtxt4;
            fields[4] =jtxt5;
            fields[5] =jtxt6;
            fields[6] =jtxt7;//then add remaining textfields
         
                for (JTextField field : fields)
                {
                     if (field.getText().equals("")) 
                     {
                     JOptionPane.showMessageDialog(null, "No data entered in " + field.getName());
                      break;
                     }
               
                }*/
           
   
            if(Check_In_Date.getTime()<Check_Out_Date.getTime())
           
            {
                JOptionPane.showMessageDialog(null,"Check out Date must be after check in date.");           
                breakloop=true;
            }

                 
     else 
    {
       if(cb4.getSelectedItem().equals("Single"))
         {
       
            tax.setText(Double.toString(daydiff * SingleRoom));
            subtotal.setText(Double.toString((daydiff * SingleRoom)));
       
            double a;
             a=Double.parseDouble(tax.getText());
        
             a = (a * 0.25)/100;
            String Tax=String.format(("Rs %.2f"),a);
            tax.setText(Tax);
        
       
            double st=Double.parseDouble(subtotal.getText());
             String SubTotal=String.format(("Rs %.2f"),st);
             subtotal.setText(SubTotal);
        
         
             total.setText(Double.toString(daydiff * SingleRoom));
             double t=Double.parseDouble(total.getText());
             String Total=String.format(("Rs %.2f"),t+a);
             total.setText(Total);
       
        
        
        if(daydiff==0)
        {
         tax.setText(Double.toString(SingleRoom));
        
         double c=Double.parseDouble(tax.getText());
        c=(c * 0.25)/100;
        String Tax1=String.format(("Rs %.2f"),c);
        tax.setText(Tax1);
        
        subtotal.setText(Double.toString((SingleRoom)-c));
        double d=(SingleRoom)-c;
        String SubTotal1;
        SubTotal1 = String.format(("Rs %.2f"),d);
        subtotal.setText(SubTotal1);
        
        total.setText(Double.toString(SingleRoom));
        double tt=Double.parseDouble(total.getText());
        String Total1=String.format(("Rs %.2f"),tt+a);
        total.setText(Total1);
        }
    }
    else if(cb4.getSelectedItem().equals("Double"))
    {
       
        tax.setText(Double.toString(daydiff * DoubleRoom));
        subtotal.setText(Double.toString((daydiff * DoubleRoom)));
       
        double a;
        a=Double.parseDouble(tax.getText());
        
        a = (a * 0.25)/100;
        String Tax=String.format(("Rs %.2f"),a);
        tax.setText(Tax);
        
       
        double st=Double.parseDouble(subtotal.getText());
        String SubTotal=String.format(("Rs %.2f"),st);
        subtotal.setText(SubTotal);
        
         
        total.setText(Double.toString(daydiff * DoubleRoom));
        double t=Double.parseDouble(total.getText());
        String Total=String.format(("Rs %.2f"),t+a);
        total.setText(Total);
        
         if(daydiff==0)
        {
         tax.setText(Double.toString(DoubleRoom));
        
         double c=Double.parseDouble(tax.getText());
        c=(c * 0.25)/100;
        String Tax1=String.format(("Rs %.2f"),c);
        tax.setText(Tax1);
        
        subtotal.setText(Double.toString((DoubleRoom)-c));
        double d=(DoubleRoom)-c;
        String SubTotal1;
        SubTotal1 = String.format(("Rs %.2f"),d);
        subtotal.setText(SubTotal1);
        
        total.setText(Double.toString(DoubleRoom));
        double tt=Double.parseDouble(total.getText());
        String Total1=String.format(("Rs %.2f"),tt+a);
        total.setText(Total1);
        }
       
    }
    else if(cb4.getSelectedItem().equals("Deluxe"))
    {
       
        tax.setText(Double.toString(daydiff * DeluxeRoom));
        subtotal.setText(Double.toString((daydiff * DeluxeRoom)));
       
        double a;
        a=Double.parseDouble(tax.getText());
        
        a = (a * 0.25)/100;
        String Tax=String.format(("Rs %.2f"),a);
        tax.setText(Tax);
        
       
        double st=Double.parseDouble(subtotal.getText());
        String SubTotal=String.format(("Rs %.2f"),st);
        subtotal.setText(SubTotal);
        
         
        total.setText(Double.toString(daydiff * DeluxeRoom));
        double t=Double.parseDouble(total.getText());
        String Total=String.format(("Rs %.2f"),t+a);
        total.setText(Total);
        
         if(daydiff==0)
        {
         tax.setText(Double.toString(SingleRoom));
        
         double c=Double.parseDouble(tax.getText());
        c=(c * 0.25)/100;
        String Tax1=String.format(("Rs %.2f"),c);
        tax.setText(Tax1);
        
        subtotal.setText(Double.toString((DeluxeRoom)-c));
        double d=(DeluxeRoom)-c;
        String SubTotal1;
        SubTotal1 = String.format(("Rs %.2f"),d);
        subtotal.setText(SubTotal1);
        
        total.setText(Double.toString(DeluxeRoom));
        double tt=Double.parseDouble(total.getText());
        String Total1=String.format(("Rs %.2f"),tt+a);
        total.setText(Total1);
        }
    }
    else if(cb4.getSelectedItem().equals("Suite"))
    {
       
        tax.setText(Double.toString(daydiff * SuiteRoom));
        subtotal.setText(Double.toString((daydiff * SuiteRoom)));
       
        double a;
        a=Double.parseDouble(tax.getText());
        
        a = (a * 0.25)/100;
        String Tax=String.format(("Rs %.2f"),a);
        tax.setText(Tax);
        
       
        double st=Double.parseDouble(subtotal.getText());
        String SubTotal=String.format(("Rs %.2f"),st);
        subtotal.setText(SubTotal);
        
         
        total.setText(Double.toString(daydiff * SuiteRoom));
        double t=Double.parseDouble(total.getText());
        String Total=String.format(("Rs %.2f"),t+a);
        total.setText(Total);
        
         if(daydiff==0)
        {
         tax.setText(Double.toString(SuiteRoom));
        
         double c=Double.parseDouble(tax.getText());
        c=(c * 0.25)/100;
        String Tax1=String.format(("Rs %.2f"),c);
        tax.setText(Tax1);
        
        subtotal.setText(Double.toString((SuiteRoom)-c));
        double d=(SuiteRoom)-c;
        String SubTotal1;
        SubTotal1 = String.format(("Rs %.2f"),d);
        subtotal.setText(SubTotal1);
        
        total.setText(Double.toString(SuiteRoom));
        double tt=Double.parseDouble(total.getText());
        String Total1=String.format(("Rs %.2f"),tt+a);
        total.setText(Total1);
        }
    }

        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
      model.addRow(new Object[]{
//      jtxt1.getText(),
      jtxt2.getText(),
      jtxt3.getText(),
      jtxt4.getText(),
      jtxt5.getText(),
      jtxt6.getText(),
      jtxt7.getText(),
      jDateChooser3.getDate(),
      jDateChooser3.getDate(),
      jDateChooser1.getDate(),
      cb1.getSelectedItem(),
      cb2.getSelectedItem(),
      cb3.getSelectedItem(),
      cb4.getSelectedItem(),
      cb5.getSelectedItem(),
      });
      
     
    }
             
    }//GEN-LAST:event_jtotalActionPerformed
              
    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
      DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
      model.setRowCount(0);
      jtxt2.setText(null);
      jtxt3.setText(null);
      jtxt4.setText(null);
      jtxt5.setText(null);
      jtxt6.setText(null);
      jtxt7.setText(null);
      jDateChooser3.setDate(null);
      jDateChooser2.setDate(null);
      jDateChooser1.setDate(null);
      cb1.setSelectedIndex(0);
      cb2.setSelectedIndex(0);
      cb3.setSelectedIndex(0);
      cb4.setSelectedIndex(0);
      cb5.setSelectedIndex(0);
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jtxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt5ActionPerformed

    private void JbtndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtndelActionPerformed
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            if(jTable1.getSelectedRow()== -1)
            {
                if(jTable1.getRowCount() == 0)
                {
                    JOptionPane.showMessageDialog(null,"No data to delete","Hotel Management System",JOptionPane.OK_OPTION);
                }
                else
                {
                    
                    JOptionPane.showMessageDialog(null,"Select a row to delete","Hotel Management System",JOptionPane.OK_OPTION);
                }    
            }
            else
            {
                model.removeRow(jTable1.getSelectedRow());
            }
int rowCount = model.getRowCount();
for (int i = rowCount - 1; i >= 0; i--) 
{
    model.removeRow(i);
}
    }//GEN-LAST:event_JbtndelActionPerformed

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxActionPerformed

    private void jtxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt6ActionPerformed

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed

        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        /*if(jTable1.getSelectedRow()== -1)
        {
            if(jTable1.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(null,"Hotel Booking update confirmed.","Hotel Management System",JOptionPane.OK_OPTION);
            }
        }*/
        
        try
        {
            Connection con=getConnection();
            PreparedStatement ps=con.prepareStatement("INSERT INTO hotel_database VALUES(?,?,?,?,?,?)");
           
            ps.setString(2,jtxt2.getText());
            ps.setString(3,jtxt3.getText());
            ps.setString(4,jtxt4.getText());
            ps.setString(5,jtxt5.getText());
            ps.setString(6,jtxt6.getText());
            ps.setString(7,jtxt7.getText());
            int i=ps.executeUpdate();
             String sql = "INSERT INTO table (column1) values(?)";
            ps=con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            ps.executeUpdate();
            boolean returnLastInsertId = false;
            if(returnLastInsertId) {
             ResultSet rs = ps.getGeneratedKeys();
              rs.next();
}
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

     /* @param args the command line arguments
     */
    protected void fetch(String id) throws SQLException
    {
        Connection con=getConnection();
        try {
            PreparedStatement  ps=con.prepareStatement("Select * from hotel_database where Customer_Ref=?");
            ps.setString(1, id);
            ResultSet rs=ps.executeQuery();
            
            while(rs.next())
            {
                jtxt2.setText(rs.getString("First_Name"));
                JOptionPane.showMessageDialog(null,"value set");
            }
        } catch (SQLException ex) {
        }
    }
    public static void main(String args[]) throws ClassNotFoundException {
  

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      java.awt.EventQueue.invokeLater(() -> {
          try {
              new Hotel_system().setVisible(true);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Hotel_system.class.getName()).log(Level.SEVERE, null, ex);
          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtndel;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JComboBox<String> cb4;
    private javax.swing.JComboBox<String> cb5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JButton jtotal;
    private javax.swing.JTextField jtxt2;
    private javax.swing.JTextField jtxt3;
    private javax.swing.JTextField jtxt4;
    private javax.swing.JTextField jtxt5;
    private javax.swing.JTextField jtxt6;
    private javax.swing.JTextField jtxt7;
    private javax.swing.JTextField jtxt8;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables


}
